import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { RichTextEditor } from "@/components/ui/rich-text-editor";
import { Sparkles, Hash } from "lucide-react";

export interface Question {
  id: string;
  text: string;
  type: "multiple-choice" | "essay" | "short-answer";
  options?: string[];
  correctAnswer?: string;
  core_ability?: string;
  isAutoGenerated?: boolean;
  isGenerating?: boolean;
  aiCommand?: string;
}

interface QuestionEditorProps {
  question: Question;
  index: number;
  onUpdate: (id: string, field: keyof Question, value: string | boolean) => void;
  onRemove: (id: string) => void;
  onGenerateAI: (id: string) => void;
}

export function QuestionEditor({
  question,
  index,
  onUpdate,
  onRemove,
  onGenerateAI,
}: QuestionEditorProps) {
  return (
    <div className="border rounded-lg p-5 bg-card shadow-sm relative overflow-hidden">
      {/* 문제 번호 인디케이터 */}
      <div className="absolute left-0 top-0 bottom-0 w-1 bg-primary/60"></div>
      
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-3">
          <Badge 
            variant="default" 
            className="text-base font-semibold px-3 py-1 h-8 flex items-center gap-1.5"
          >
            <Hash className="h-4 w-4" />
            {index + 1}
          </Badge>
          <div className="h-6 w-px bg-border"></div>
          <span className="text-sm text-muted-foreground">문제 출제 중</span>
        </div>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={(e) => {
            e.preventDefault();
            onRemove(question.id);
          }}
          className="text-destructive hover:text-destructive hover:bg-destructive/10"
        >
          삭제
        </Button>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label>문제 유형</Label>
          <select
            value={question.type}
            onChange={(e) =>
              onUpdate(question.id, "type", e.target.value)
            }
            className="w-full p-2 border rounded-md"
          >
            <option value="essay">Problem Solving Type</option>
            <option value="short-answer">STEM Problem Type</option>
            <option value="multiple-choice" disabled>
              Type C
            </option>
          </select>
        </div>
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <Label>시험 문제</Label>
            <div className="flex items-center gap-2">
              {question.isAutoGenerated && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={(e) => {
                    e.preventDefault();
                    onGenerateAI(question.id);
                  }}
                  disabled={question.isGenerating}
                >
                  {question.isGenerating ? "생성 중..." : "재생성"}
                </Button>
              )}
              <div className="flex items-center gap-2">
                <Label
                  htmlFor={`auto-generate-${question.id}`}
                  className="text-sm"
                >
                  <Sparkles className="w-4 h-4 text-primary" />
                  AI 스마트 생성
                </Label>
                <Switch
                  id={`auto-generate-${question.id}`}
                  checked={question.isAutoGenerated || false}
                  onCheckedChange={(checked) => {
                    if (checked && !question.text) {
                      onGenerateAI(question.id);
                    } else {
                      onUpdate(question.id, "isAutoGenerated", checked);
                    }
                  }}
                />
              </div>
            </div>
          </div>
          {question.isGenerating && (
            <div className="flex items-center justify-center p-4 bg-blue-50 border border-blue-200 rounded-md mb-2">
              <div className="flex items-center gap-2 text-blue-600">
                <div className="animate-spin rounded-full h-4 w-4 border-2 border-blue-600 border-t-transparent"></div>
                <span className="text-sm font-medium">
                  AI가 문제를 생성하고 있습니다...
                </span>
              </div>
            </div>
          )}
          <RichTextEditor
            value={question.text}
            onChange={(value) => onUpdate(question.id, "text", value)}
            placeholder={
              question.isAutoGenerated
                ? "AI가 자동으로 생성한 문제입니다. 필요시 수정하세요."
                : "여기에 문제를 입력하세요..."
            }
            className="min-h-[300px]"
          />
          {question.isAutoGenerated && (
            <div className="space-y-2 mt-3">
              <Label>AI 명령어</Label>
              <div className="flex gap-2">
                <Input
                  value={question.aiCommand || ""}
                  onChange={(e) =>
                    onUpdate(question.id, "aiCommand", e.target.value)
                  }
                  placeholder="예: 이 문제를 더 어렵게 만들어줘, 또는 다른 예시를 들어서 설명해줘"
                  className="flex-1"
                />
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={(e) => {
                    e.preventDefault();
                    onGenerateAI(question.id);
                  }}
                  disabled={
                    question.isGenerating || !question.aiCommand?.trim()
                  }
                >
                  {question.isGenerating ? "수정 중..." : "적용"}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                AI에게 문제 수정이나 개선을 요청할 수 있습니다.
              </p>
            </div>
          )}
        </div>
        <div className="space-y-2">
          <Label>문제 핵심 역량</Label>
          <Textarea
            value={question.core_ability}
            onChange={(e) =>
              onUpdate(question.id, "core_ability", e.target.value)
            }
            placeholder="여기에 문제 핵심 역량을 입력하세요..."
            rows={7}
            className="min-h-[100px]"
          />
        </div>
      </div>
    </div>
  );
}

