/** Shared grading/score utility functions */

/** Returns Tailwind color class based on score percentage (0-100) */
export function getScoreColor(score: number): string {
  if (score >= 90) return "text-green-600 dark:text-green-400";
  if (score >= 80) return "text-blue-600 dark:text-blue-400";
  if (score >= 70) return "text-yellow-600 dark:text-yellow-400";
  return "text-red-600 dark:text-red-400";
}

/** Returns Tailwind color class based on score relative to maxScore */
export function getScoreColorRelative(score: number | null, maxScore: number | null): string {
  if (score === null || maxScore === null) return "text-muted-foreground";
  const percentage = (score / maxScore) * 100;
  return getScoreColor(percentage);
}

/** Returns Tailwind badge class for exam session status */
export function getStatusColor(status: string): string {
  switch (status) {
    case "completed":
      return "bg-green-500/10 text-green-700 dark:text-green-400 border-green-500/20";
    case "in-progress":
      return "bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-500/20";
    default:
      return "bg-muted text-muted-foreground";
  }
}

/** Formats a date string to Korean locale */
export function formatDateKo(dateString: string | null): string {
  if (!dateString) return "날짜 없음";
  return new Date(dateString).toLocaleDateString("ko-KR", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/** Checks if a grade was auto-generated by AI based on grade_type column (preferred) or comment pattern (fallback) */
export function isAiGraded(grade: { grade_type?: string; comment?: string | null }): boolean {
  if (grade.grade_type) return grade.grade_type === "auto";
  // Fallback: pattern matching for legacy data without grade_type
  if (!grade.comment) return false;
  return /(채팅 단계|답안 단계|피드백 단계)/.test(grade.comment);
}
