/** Shared grading/score utility functions */

export const ASSIGNMENT_GRADE_SCORES = {
  excellent: 85,
  average: 70,
  insufficient: 45,
} as const;

export type AssignmentGradeLabel = "우수" | "평범" | "미흡";

export function scoreToAssignmentLabel(score: number | null | undefined): AssignmentGradeLabel {
  if (typeof score !== "number" || !Number.isFinite(score)) return "미흡";
  if (score >= 78) return "우수";
  if (score >= 58) return "평범";
  return "미흡";
}

export function assignmentLabelToScore(label: AssignmentGradeLabel): number {
  switch (label) {
    case "우수":
      return ASSIGNMENT_GRADE_SCORES.excellent;
    case "평범":
      return ASSIGNMENT_GRADE_SCORES.average;
    case "미흡":
      return ASSIGNMENT_GRADE_SCORES.insufficient;
  }
}

export function normalizeAssignmentGradeScore(score: number): number {
  return assignmentLabelToScore(scoreToAssignmentLabel(score));
}

export function getAssignmentGradeDescription(label: AssignmentGradeLabel): string {
  switch (label) {
    case "우수":
      return "채팅 리서치 과정, 근거 검증, 퀴즈 이해도 신호가 전반적으로 좋습니다.";
    case "평범":
      return "기본적인 리서치 수행은 보이나 근거 검증이나 자기주도적 판단이 일부 부족합니다.";
    case "미흡":
      return "리서치 과정, 근거 확인, 이해도 신호가 부족하거나 AI 의존이 큽니다.";
  }
}

/** Returns Tailwind color class based on score percentage (0-100) */
export function getScoreColor(score: number): string {
  if (score >= 90) return "text-green-600 dark:text-green-400";
  if (score >= 80) return "text-blue-600 dark:text-blue-400";
  if (score >= 70) return "text-yellow-600 dark:text-yellow-400";
  return "text-red-600 dark:text-red-400";
}

/** Returns Tailwind color class based on score relative to maxScore */
export function getScoreColorRelative(score: number | null, maxScore: number | null): string {
  if (score === null || maxScore === null || maxScore === 0) return "text-muted-foreground";
  const percentage = (score / maxScore) * 100;
  return getScoreColor(percentage);
}

/** Returns Tailwind badge class for exam session status */
export function getStatusColor(status: string): string {
  switch (status) {
    case "completed":
      return "bg-green-500/10 text-green-700 dark:text-green-400 border-green-500/20";
    case "in-progress":
      return "bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-500/20";
    case "quiz-pending":
      return "bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/20";
    default:
      return "bg-muted text-muted-foreground";
  }
}

/** Formats a date string to Korean locale */
export function formatDateKo(dateString: string | null): string {
  if (!dateString) return "날짜 없음";
  return new Date(dateString).toLocaleDateString("ko-KR", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/**
 * Checks if a grade was auto-generated by AI.
 * Primary: grade_type === "auto" (always set since the grade_type bug fix).
 * Fallback: comment pattern matching for legacy rows created before the fix
 * (see sql/004_fix_auto_grade_type.sql for data migration).
 */
export function isAiGraded(grade: { grade_type?: string; comment?: string | null }): boolean {
  if (grade.grade_type) return grade.grade_type === "auto";
  if (!grade.comment) return false;
  return /(채팅 단계|답안 단계|피드백 단계)/.test(grade.comment);
}
