"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { useRouter } from "next/navigation";

export default function CreateExam() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [examData, setExamData] = useState({
    title: "",
    description: "",
    duration: 60,
    code: "",
    materials: [] as File[],
    instructions: "", // AI 프롬프트 추가
  });
  const [questions, setQuestions] = useState<Question[]>([]);

  interface Question {
    id: string;
    text: string;
    type: "multiple-choice" | "essay" | "short-answer";
    options?: string[];
    correctAnswer?: string;
    core_ability?: string; // 문제 핵심 역량 - AI 프롬프트에 사용
    isAutoGenerated?: boolean; // 자동 생성 여부
    isGenerating?: boolean; // AI 생성 중 상태
    aiCommand?: string; // AI에게 내릴 명령어
  }

  const generateExamCode = () => {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let result = "";
    for (let i = 0; i < 6; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    setExamData((prev) => ({ ...prev, code: result }));
  };

  const generateQuestionWithAI = async (questionId: string) => {
    if (!examData.title || !examData.description) {
      alert("시험 제목과 설명을 먼저 입력해주세요.");
      return;
    }

    const currentQuestion = questions.find((q) => q.id === questionId);
    if (!currentQuestion) return;

    // 해당 문제의 로딩 상태 설정
    setQuestions(
      questions.map((q) =>
        q.id === questionId ? { ...q, isGenerating: true } : q
      )
    );

    try {
      let prompt;

      if (currentQuestion.aiCommand && currentQuestion.aiCommand.trim()) {
        // AI 명령어가 있는 경우 - 기존 문제를 수정
        prompt = `당신은 전문 시험 출제자입니다. 다음 정보를 바탕으로 기존 문제를 수정해주세요.

시험 정보:
- 제목: ${examData.title}
- 설명: ${examData.description}
- 시간: ${examData.duration}분
${examData.instructions ? `- AI 설정: ${examData.instructions}` : ""}

기존 문제:
${currentQuestion.text}

수정 요청: ${currentQuestion.aiCommand}

요구사항:
1. 기존 문제를 바탕으로 사용자의 요청사항을 반영하여 수정하세요.
2. 문제의 교육적 가치를 유지하면서 요청사항을 충족시키세요.
3. 정답을 직접 제공하지 말고, 학생이 사고력을 발휘할 수 있도록 하세요.
4. 수정된 문제의 핵심 역량을 함께 제안해주세요.

응답 형식:
문제: [수정된 문제 내용]

핵심 역량: [문제의 핵심 역량 설명]`;
      } else {
        // AI 명령어가 없는 경우 - 새 문제 생성
        prompt = `당신은 전문 시험 출제자입니다. 다음 정보를 바탕으로 적절한 시험 문제를 1개 생성해주세요.

시험 정보:
- 제목: ${examData.title}
- 설명: ${examData.description}
- 시간: ${examData.duration}분
${examData.instructions ? `- AI 설정: ${examData.instructions}` : ""}

요구사항:
1. 시험의 난이도와 내용에 맞는 적절한 문제를 생성하세요.
2. 문제는 명확하고 교육적으로 의미 있어야 합니다.
3. 정답을 직접 제공하지 말고, 학생이 사고력을 발휘할 수 있도록 하세요.
4. 문제의 핵심 역량을 함께 제안해주세요.

응답 형식:
문제: [생성된 문제 내용]

핵심 역량: [문제의 핵심 역량 설명]`;
      }

      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: prompt,
          sessionId: "temp_generate_question",
          examTitle: examData.title,
          examCode: examData.code,
        }),
      });

      if (!response.ok) {
        throw new Error("AI 문제 생성에 실패했습니다.");
      }

      const data = await response.json();
      const aiResponse = data.response;

      // AI 응답에서 문제와 핵심 역량을 파싱
      const problemMatch = aiResponse.match(/문제:\s*(.+?)(?:\n|$)/);
      const coreAbilityMatch = aiResponse.match(/핵심 역량:\s*(.+?)(?:\n|$)/);

      const problemText = problemMatch ? problemMatch[1].trim() : aiResponse;
      const coreAbilityText = coreAbilityMatch
        ? coreAbilityMatch[1].trim()
        : "문제 해결 능력";

      // 해당 문제 업데이트
      setQuestions(
        questions.map((q) =>
          q.id === questionId
            ? {
                ...q,
                text: problemText,
                core_ability: coreAbilityText,
                isAutoGenerated: true,
                isGenerating: false,
                aiCommand:
                  currentQuestion.aiCommand && currentQuestion.aiCommand.trim()
                    ? "" // 명령어 사용 후 초기화
                    : q.aiCommand,
              }
            : q
        )
      );
    } catch (error) {
      console.error("AI 문제 생성 오류:", error);
      alert("문제 생성 중 오류가 발생했습니다. 다시 시도해주세요.");

      // 에러 발생 시 로딩 상태 해제
      setQuestions(
        questions.map((q) =>
          q.id === questionId ? { ...q, isGenerating: false } : q
        )
      );
    }
  };

  // 페이지 진입 시 자동으로 시험 코드 생성
  useEffect(() => {
    generateExamCode();
  }, []);

  const validateFile = (file: File): boolean => {
    const allowedTypes = [
      "application/pdf",
      "application/vnd.ms-powerpoint",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp",
    ];

    const maxSize = 10 * 1024 * 1024; // 10MB

    if (!allowedTypes.includes(file.type)) {
      alert(
        "지원되지 않는 파일 형식입니다. PDF, PPT, 워드, 이미지 파일만 업로드 가능합니다."
      );
      return false;
    }

    if (file.size > maxSize) {
      alert("파일 크기가 10MB를 초과합니다.");
      return false;
    }

    return true;
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    const validFiles = files.filter(validateFile);

    setExamData((prev) => ({
      ...prev,
      materials: [...prev.materials, ...validFiles],
    }));

    // Reset input
    e.target.value = "";
  };

  const removeFile = (index: number) => {
    setExamData((prev) => ({
      ...prev,
      materials: prev.materials.filter((_, i) => i !== index),
    }));
  };

  const getFileIcon = (fileName: string) => {
    const extension = fileName.split(".").pop()?.toLowerCase();
    switch (extension) {
      case "pdf":
        return "📄";
      case "ppt":
      case "pptx":
        return "📊";
      case "doc":
      case "docx":
        return "📝";
      case "jpg":
      case "jpeg":
      case "png":
      case "gif":
      case "webp":
        return "🖼️";
      default:
        return "📎";
    }
  };

  const addQuestion = () => {
    const newQuestion: Question = {
      id: Date.now().toString(),
      text: "",
      type: "essay",
      core_ability: "", // 문제 핵심 역량 초기화
      isAutoGenerated: false, // 기본적으로 직접쓰기 모드
    };
    setQuestions([...questions, newQuestion]);
  };

  const updateQuestion = (
    id: string,
    field: keyof Question,
    value: string | boolean
  ) => {
    setQuestions(
      questions.map((q) => (q.id === id ? { ...q, [field]: value } : q))
    );
  };

  const removeQuestion = (id: string) => {
    setQuestions(questions.filter((q) => q.id !== id));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!examData.title || !examData.code || questions.length === 0) return;

    setIsLoading(true);

    try {
      let materialUrls: string[] = [];

      // Upload files to Supabase Storage if any materials exist
      if (examData.materials.length > 0) {
        const uploadPromises = examData.materials.map(async (file) => {
          const fileName = `${Date.now()}-${file.name}`;
          const formData = new FormData();
          formData.append("file", file);
          formData.append("fileName", fileName);

          const uploadResponse = await fetch("/api/upload", {
            method: "POST",
            body: formData,
          });

          if (!uploadResponse.ok) {
            throw new Error(`Failed to upload ${file.name}`);
          }

          const uploadResult = await uploadResponse.json();
          return uploadResult.url;
        });

        materialUrls = await Promise.all(uploadPromises);
      }

      // Prepare exam data for database
      const examDataForDB = {
        title: examData.title,
        code: examData.code,
        description: examData.description,
        duration: examData.duration,
        instructions: examData.instructions,
        questions: questions,
        materials: materialUrls, // Array of file URLs
        status: "draft", // Start as draft
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };

      // Save to Supabase
      const response = await fetch("/api/supa", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          action: "create_exam",
          data: examDataForDB,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        console.error("API Error:", errorData);
        throw new Error(
          `Failed to create exam: ${errorData.error || "Unknown error"}`
        );
      }

      const result = await response.json();
      console.log("Exam created successfully:", result);

      // Redirect to exam management page
      router.push("/instructor/exams");
    } catch (error) {
      console.error("Error creating exam:", error);
      alert("시험 생성 중 오류가 발생했습니다. 다시 시도해주세요.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container mx-auto p-6 max-w-4xl">
      <div className="mb-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold">새로운 시험 만들기</h1>
            <p className="text-muted-foreground">
              문제와 설정으로 새로운 시험을 구성하세요
            </p>
          </div>
        </div>
      </div>

      <form
        onSubmit={handleSubmit}
        onKeyDown={(e) => {
          // textarea에서는 엔터 허용, 다른 입력 요소에서는 form submit 방지
          if (
            e.key === "Enter" &&
            (e.target as HTMLElement).tagName !== "TEXTAREA"
          ) {
            e.preventDefault();
          }
        }}
        className="space-y-6"
      >
        {/* Basic Exam Info */}
        <Card>
          <CardHeader>
            <CardTitle>시험 정보</CardTitle>
            <CardDescription>시험의 기본 세부사항</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="title">시험 제목</Label>
                <Input
                  id="title"
                  value={examData.title}
                  onChange={(e) =>
                    setExamData((prev) => ({ ...prev, title: e.target.value }))
                  }
                  placeholder="예) 국제경영론 25-1 중간고사"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="code">시험 코드</Label>
                <div className="flex gap-2">
                  <Input
                    id="code"
                    value={examData.code}
                    onChange={(e) =>
                      setExamData((prev) => ({
                        ...prev,
                        code: e.target.value.toUpperCase(),
                      }))
                    }
                    placeholder={examData.code}
                    className="font-mono"
                    required
                    disabled
                  />
                  <Button
                    type="button"
                    variant="outline"
                    onClick={(e) => {
                      e.preventDefault();
                      generateExamCode();
                    }}
                  >
                    재생성
                  </Button>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="description">시험 관련 지침</Label>
              <Textarea
                id="description"
                value={examData.description}
                onChange={(e) =>
                  setExamData((prev) => ({
                    ...prev,
                    description: e.target.value,
                  }))
                }
                placeholder="시험에 대한 간단한 설명"
                rows={6}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="duration">시험 시간 (분)</Label>
              <Input
                id="duration"
                type="number"
                value={examData.duration}
                onChange={(e) =>
                  setExamData((prev) => ({
                    ...prev,
                    duration: parseInt(e.target.value),
                  }))
                }
                min="15"
                max="480"
              />
            </div>
          </CardContent>
        </Card>

        {/* AI Configuration */}
        <Card>
          <CardHeader>
            <CardTitle>인공지능 설정</CardTitle>
            <CardDescription>
              AI 도우미의 행동 방식과 학습 자료 설정
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="instructions">인공지능 설정</Label>
              <Textarea
                id="instructions"
                value={examData.instructions}
                onChange={(e) =>
                  setExamData((prev) => ({
                    ...prev,
                    instructions: e.target.value,
                  }))
                }
                placeholder="여기에 AI 프롬프트를 입력하세요..."
                rows={8}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="materials">수업 자료</Label>
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <Input
                    id="materials"
                    type="file"
                    multiple
                    accept=".pdf,.ppt,.pptx,.doc,.docx,.jpg,.jpeg,.png,.gif,.webp"
                    onChange={handleFileSelect}
                    className="hidden"
                  />
                  <Label
                    htmlFor="materials"
                    className="flex items-center gap-2 px-4 py-2 border border-dashed border-gray-300 rounded-md cursor-pointer hover:border-gray-400 transition-colors"
                  >
                    📎 파일 선택
                  </Label>
                  <span className="text-sm text-muted-foreground">
                    PDF, PPT, 워드, 이미지 파일 (최대 10MB)
                  </span>
                </div>

                {examData.materials.length > 0 && (
                  <div className="space-y-2">
                    <Label className="text-sm font-medium">
                      업로드된 파일:
                    </Label>
                    <div className="space-y-1">
                      {examData.materials.map((file, index) => (
                        <div
                          key={index}
                          className="flex items-center justify-between p-2 bg-gray-50 rounded-md"
                        >
                          <div className="flex items-center gap-2">
                            <span className="text-lg">
                              {getFileIcon(file.name)}
                            </span>
                            <span className="text-sm font-medium">
                              {file.name}
                            </span>
                            <span className="text-xs text-muted-foreground">
                              ({(file.size / 1024 / 1024).toFixed(1)}MB)
                            </span>
                          </div>
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeFile(index)}
                          >
                            ✕
                          </Button>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Questions */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>문제</CardTitle>
                <CardDescription>시험에 문제를 추가하세요</CardDescription>
              </div>
              <Button
                type="button"
                onClick={(e) => {
                  e.preventDefault();
                  addQuestion();
                }}
              >
                문제 추가
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            {questions.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                <p>아직 추가된 문제가 없습니다.</p>
                <p>&quot;문제 추가&quot;를 클릭하여 시작하세요!</p>
              </div>
            ) : (
              <div className="space-y-6">
                {questions.map((question, index) => (
                  <div key={question.id} className="border rounded-lg p-4">
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="font-semibold">문제 {index + 1}</h3>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={(e) => {
                          e.preventDefault();
                          removeQuestion(question.id);
                        }}
                      >
                        삭제
                      </Button>
                    </div>
                    <div className="space-y-4">
                      <div className="space-y-2">
                        <Label>문제 유형</Label>
                        <select
                          value={question.type}
                          onChange={(e) =>
                            updateQuestion(question.id, "type", e.target.value)
                          }
                          className="w-full p-2 border rounded-md"
                        >
                          <option value="essay">Problem Solving Type</option>
                          <option value="short-answer" disabled>
                            Type B
                          </option>
                          <option value="multiple-choice" disabled>
                            Type C
                          </option>
                        </select>
                      </div>
                      <div className="space-y-2">
                        <div className="flex items-center justify-between">
                          <Label>시험 문제</Label>
                          <div className="flex items-center gap-2">
                            {question.isAutoGenerated && (
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={(e) => {
                                  e.preventDefault();
                                  generateQuestionWithAI(question.id);
                                }}
                                disabled={question.isGenerating}
                              >
                                {question.isGenerating
                                  ? "생성 중..."
                                  : "재생성"}
                              </Button>
                            )}
                            <div className="flex items-center gap-2">
                              <Label
                                htmlFor={`auto-generate-${question.id}`}
                                className="text-sm"
                              >
                                자동생성
                              </Label>
                              <Switch
                                id={`auto-generate-${question.id}`}
                                checked={question.isAutoGenerated || false}
                                onCheckedChange={(checked) => {
                                  if (checked && !question.text) {
                                    // 스위치 ON이고 내용이 비어있으면 AI 생성 실행
                                    generateQuestionWithAI(question.id);
                                  } else {
                                    // 스위치 상태 업데이트
                                    updateQuestion(
                                      question.id,
                                      "isAutoGenerated",
                                      checked
                                    );
                                  }
                                }}
                              />
                            </div>
                          </div>
                        </div>
                        {question.isGenerating && (
                          <div className="flex items-center justify-center p-4 bg-blue-50 border border-blue-200 rounded-md mb-2">
                            <div className="flex items-center gap-2 text-blue-600">
                              <div className="animate-spin rounded-full h-4 w-4 border-2 border-blue-600 border-t-transparent"></div>
                              <span className="text-sm font-medium">
                                AI가 문제를 생성하고 있습니다...
                              </span>
                            </div>
                          </div>
                        )}
                        <Textarea
                          value={question.text}
                          onChange={(e) =>
                            updateQuestion(question.id, "text", e.target.value)
                          }
                          placeholder={
                            question.isAutoGenerated
                              ? "AI가 자동으로 생성한 문제입니다. 필요시 수정하세요."
                              : "여기에 문제를 입력하세요..."
                          }
                          rows={8}
                          className="min-h-[300px]"
                        />
                        {question.isAutoGenerated && (
                          <div className="space-y-2 mt-3">
                            <Label>AI 명령어</Label>
                            <div className="flex gap-2">
                              <Input
                                value={question.aiCommand || ""}
                                onChange={(e) =>
                                  updateQuestion(
                                    question.id,
                                    "aiCommand",
                                    e.target.value
                                  )
                                }
                                placeholder="예: 이 문제를 더 어렵게 만들어줘, 또는 다른 예시를 들어서 설명해줘"
                                className="flex-1"
                              />
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={(e) => {
                                  e.preventDefault();
                                  generateQuestionWithAI(question.id);
                                }}
                                disabled={
                                  question.isGenerating ||
                                  !question.aiCommand?.trim()
                                }
                              >
                                {question.isGenerating ? "수정 중..." : "적용"}
                              </Button>
                            </div>
                            <p className="text-xs text-muted-foreground">
                              AI에게 문제 수정이나 개선을 요청할 수 있습니다.
                            </p>
                          </div>
                        )}
                      </div>
                      <div className="space-y-2">
                        <Label>문제 핵심 역량</Label>
                        <Textarea
                          value={question.core_ability}
                          onChange={(e) =>
                            updateQuestion(
                              question.id,
                              "core_ability",
                              e.target.value
                            )
                          }
                          placeholder="여기에 문제 핵심 역량을 입력하세요..."
                          rows={7}
                          className="min-h-[100px]"
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Submit */}
        <div className="flex gap-4">
          <Button
            type="button"
            variant="outline"
            onClick={() => router.push("/instructor")}
          >
            취소
          </Button>
          <Button
            type="submit"
            disabled={
              isLoading ||
              !examData.title ||
              !examData.code ||
              questions.length === 0
            }
          >
            {isLoading ? "만들기 중..." : "시험 만들기"}
          </Button>
        </div>
      </form>
    </div>
  );
}
